version: "3"
services:
  frontend:
    image: node:16.6.1-alpine
    working_dir: /code
    user: node
    volumes:
      - .:/code
    command: sh -c 'npm install && npm run start'
    network_mode: "host"
