name: Commit Lint Check

on: [push]

jobs:
  build:
    name: Commit Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Lint Commits
        uses: Ferlab-Ste-Justine/action-commit-lint@v2
