name: 'Quality'

on:
    pull_request:
        branches:
            - dev
            - main

permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write

jobs:
  tests:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: true
        - uses: actions/setup-node@v4
          with:
            node-version-file: '.nvmrc'
            cache: 'npm'
        - name: Install modules
          run: npm ci
        - name: Run tests
          id: tests
          run: |
            echo " " >> results.log
            echo "## Project Coverage and Test" >> results.log
            echo "" >> results.log
            echo "`npm run test:github  2>&1 | sed 's/=//g' | tail -n 11`" >> results.log
            echo " " >> results.log
        - uses: marocchino/sticky-pull-request-comment@v2
          with:
            header: Project Coverage and Test
            path: results.log
